---
title: "Draft: Conclict of Interest"
author: "Mark van der Loo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Roles and Responsibilities}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

_This document is a proposal does not (yet) reflect current policy of the R Journal_

## What is a conflict of interest?

For the R Journal, it is important that all decisions on papers are taken 
based as much as possible on objective arguments. A conflict of interest is
any situation that may hamper the objectivity of such a decision. Examples
are:

- you are a (past) collaborator in the work discussed in the submission
- you are a (past) collaborator in a work that somehow competes with the submission
- one or more of the authors of the submission is a (past) co-author or collaborator
- one or more of the authors are (close) friends, family, or colleagues
- one of the authors has (had) influence on your professional life, for example via funding.


## What to do in case of conflict of interest?

The most important principle is to be transparent.

### For Associate Editors

If you are asked to handle a paper, and you feel there may be a conflict of
interest, always consult the handling executive editor. The EE will decide
whether someone else needs to handle the submission. Regardless of the
decision, the notification and decision will be archived by the EE.

### For editors

If you are asked to handle a paper, and you feel there may be a conflict of
interest, consult the Editor-in-Chief. The EE will decide whether someone else
needs to handle the submission. Regardless of the decision, the notification
and decision will be archived by the EE.

### For the Editor-in-Chief

If a submission comes in and you feel there may be a conflict of interest,
never handle the paper yourself. Hand it over to an EE and explain and archive
the conflict of interest.


## How to archive a conflict of interest

Conflicts of interest, and decisions surrounding conflict of interest should be described in
a plain text file called `conflicts.txt` and stored in the `correspondence` folder
with the submission. The description should at least contain:

- Date
- Reason for possible conflict of interest
- Decision of the executive editor 













