---
title: "Guide to Building an Issue"
author: "Di Cook"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Guide to Building an Issue}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE, 
  warning = FALSE,
  message = FALSE
)
```


# Articles to include

All articles accepted up to the publication dates: Mar 31, Jun 30, Oct 31, Dec 31, should be included. (Traditionally these articles would first be made available online, but with the increased frequency of publication we are not at the moment performing this step.)

# Preparation

- Copy editing of the accepted articles.
- Collect news items into the "News_items" directory under the matching issue number.

# Building an issue

## Steps

1. Copy articles from Accepted into Proofs (using `rj:::make_proof()`): 
  - You need to provide the issue number, eg "2022-2".
  - It will move accepted articles that have the current status "proofed".
  - It will copy news articles with the matching issue number from "News_items"
2. Copy files across to `rjournal.github.io`, using `rj:::publish_issue()`. This function will publish all articles and news for this issue, and create an issue file. The issue file is used to enter information about the editors and issue, and rendering it will create the HTML listing of articles and combined PDF issue. Articles can be individually published and updated with `rj:::publish_article()`, news can also be individually published and updated with `rj:::publish_news()`.
  - This article publishing process will create the zip file of supplementary material from the list of files in the DESCRIPTION
  - The will also assign a "slug" the id of the published article, which is added to the DESCRIPTION file in the Proofs folder. 
  - This slug will be used for the folder name in the `rjournal.github.io` "_articles" folder.
  - Also creates an issue containing `volume-issue.Rmd` (eg `2022-2.Rmd`) in the "_issues" folder.
  - Renders each article (this can cause errors if the article isn't reproducible).
3. Update and render the issue, using the file `volume-issue.Rmd` in the "_issues" folder.
  - It generates a folder within "_issues" with the information on organising the articles in the issue
  - This will also generate the `doi.xml` used to register DOIs with <crossref.org>.
4. Push the changes to GitHub. A preview of the deploy is available at <rjournal.github.io> when changes are pushed to the master branch. A deploy to <journal.r-project.org> occurs when a change is pushed to the published branch (do a pull request from master to published).
4. Register the DOIs with `crossref.org`.
