---
title: "Draft: Roles and Responsibilities"
author: "Mark van der Loo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Roles and Responsibilities}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

_This document is a proposal does not (yet) reflect current policy of the R Journal_


This vignette gives an overview of the roles in the R Journal editorial team,
the responsibilities that come with each role, and an overview of the editorial
process. There are separate guides that detail the operational and technical
details, in particular: 

- [Associate Editor Guide](associate_editors_guide.html)
- [Executive Editor Guide](executive_editors_guide.html)
- [Editor in Chief Guide](editor_in_chief_guide.html)

All editors are expected to take appropriate action in the case of conflict of 
interest. See the [conflict of interest policy](conflict_of_interest.html)


## Roles and responsibilities in the editorial team

The editorial team consists of four Executive Editors (EE), of which one is the
Editor-in-Chief (EIC). The EEs are supported by a team of Associate Editors.

The team of EEs follow a rotating schedule. A new member will act as EE for 2
years, takes the role of EIC in year 3 and returns to EE for their last year.

AEs are in principle appointed for three years, but extensions are possible if
both the EEs and AE agree.

All memmbers of the editorial team are responsible for signalling possible conflicts
of interest. See the [conflict ]


### Editor-in-Chief

The EIC is responsible for

- Quality and publication of the Journal 
- Timely and proper handling of submitted papers
- Ensure staffing of the EE and AE teams.
- Resolving conflicts between authors and the Journal, where necessary in collaboration with the advisory board.

In particular, the EIC distributes the article workload amongst the EEs. The
EIC organizes biweekly meetings for the EE team, monthly meetings for the AE
team, and an annual meeting with the advisory board. The EIC also ensures that
there are always four EEs and sufficient AEs to handle the workload. Finally,
the EIC ensures that the quarterly issues are produced and published.


### Exectutive Editors

An EE is responsible for

- Proper and timely handling of papers under their responsibility.
- Take the editorial decision (Accept/Minor/Major/Reject) for papers under their responsibility and
  communicate with the authors.
- Supporting the EIC in recruiting AEs and EEs.

In particular, the EE communicates with AE and with the authors of submissions.
They ensure that both the reviews, and the decision on submissions are properly
argued and that this argumentation is both archived and communicated to the
authors. 

EEs may choose to hand over a paper to an AE but they will typically also
handle papers themselves. For those papers the EE also takes on the
responisbilities of an AE.


### Associate Editors

An AE is responsible for

- Finding and recruiting appropriate reviewers, such that there are preferably at least two reviews of sufficient quality for each submission.
- Ensure that both the article contents and the code are sufficiently reviewed.
- Ensure timely handling of papers under their responsibility
- Advise the EE on the editorial decision (Accept/Minor/Major/Reject)


----

## Editorial Procedure

When handling a new submission, there are several points of decision. Here we
detail who takes each decision and in which order. The way decisions are made
can be found in the AE, EE and EIC guides.

When a (re)submission arrives

1. **The EIC decides whether it can be assigned to an EE.** The decision is based
   on technical checks, including completness, formatting, and reproducibility. 
   If the checks are not passed, the paper is rejected and the authors could be
   asked to possibly resubmit. If all checks pass, the EIC assigns the paper to an
   EE.
2. **The EE decides whether the submission is of sufficient quality for review.**
3. The paper is assigned to an AE or handled by the EE.
    a. Reviewers are recruited by EE or AE. They ensure that enough reviews of sufficient quality 
       are obtained. 
    b. If an AE handles the paper, the AE advises the EE on a decision.
4. **The EE decides whether the reviews are of sufficient quality to support an argued decision**. 
   Reviews should be clear, objective, and together cover both the paper and the R code.
5. **The EE takes the editorial decision: Accept/Minor revision/Major revision/Reject**. The
   EE also archives the decision and communicates it with the authors.








