---
title: "Special Issue Rules and Guidelines"
author: "Michael Kane"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Operating procedures for the editors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

This year (2020), the R Journal Editors are piloting a special issue
of the R Journal that will allow R Finance and R Medicine speakers to 
publish their work. The R Journal is now in the [top 17 journals in 
statistics and probability](https://www.scimagojr.com/journalrank.php?category=2613) 
by impact factor. The special issue is meant to allow conference organizers
to use the R Journal's publication infrastructure to disseminate research
and analyses presented at the conference to a wider audience. It is
also meant for speakers to get publication credit for their effort. A special
issue article  can be considered to be a journal article and generally carries more weight than 
conference proceedings.

# Conference Editor in Chief

Conference committees will designate a "Conference Editor in Chief" (CEiC) who
will be primarily responsible for putting the special issue together. For 
this pilot to be successful, it is important that putting together the
special issue does not significantly increase the workload of the regular
editors or the administrative team that helps to build the issues. It
will be the responsibility of the CEiC to identify associate editors if needed,
assign reviewers, accept and reject papers, and assemble the special issue.
It will also be the responsibility of the CEiC to make sure that the issue reflects the diversity of the community, and that the
[R Consortium and R Community Code of Conduct](https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct) 
is followed during the process. 

# Suggested Format

The R Journal has traditionally consisted of relatively short, concise articles
and this format is welcome for the special issue. To minimize the time
required in the review cycle, we suggest accepting papers that are 
approximately 5 -- 12 pages. It may also be helpful to point out that papers 
should document the talks and the reviewers should evaluate the paper in the 
context in which it was written and provide suggestions to improve it. Authors will need to adhere to the R Journal author guidelines, so that issue build is streamlined.

We also suggest having those conference speakers submitting a paper also act 
as reviewers. One of the CEiC's goals should be to get the issue out 
in a timely manner. Submitters are then incentivized to provide a short
turnaround time and are likely the most qualified to evaluate the work
of their community peers.

